version: '3.8'
services:
  nodejs:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    networks:
      - node_network
networks:
  node_network:
    driver: bridge
